# .pre-commit-config.yaml
# OpenFreqBench baseline hooks
default_language_version:
  python: python3

repos:
  # Lightweight hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
